name = "CrmMockAdapter"
uuid = "83f0a022-9340-4280-be6d-294ace2c1a01"
authors = ["Rulia Demo"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
